apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-pipeline
spec:
  replicas: 1
  selector:
    app: myapp
  template:
    metadata:
      labels: myapp
    spec:
      containers:
        - name: container1
          image: manjirinaik/myapp
          ports:
          - continerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: nodePort
  selector:
    app: myapp
  ports:
    - port: 80
      containerPort: 80